In [38]:
from scipy.stats import shapiro, normaltest, anderson, kstest
import polars as pl
import numpy as np
from tqdm import tqdm

In [3]:
df = pl.read_parquet('keyed_data.parquet')

In [4]:
df.head()

shape: (5, 513)
┌──────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ KEY  ┆ dim_0     ┆ dim_1     ┆ dim_2     ┆ … ┆ dim_508   ┆ dim_509   ┆ dim_510   ┆ dim_511   │
│ ---  ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str  ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4514 ┆ 0.00764   ┆ -0.077151 ┆ 0.031879  ┆ … ┆ 0.001612  ┆ -0.012929 ┆ -0.009272 ┆ -0.049731 │
│ 4514 ┆ -0.000693 ┆ -0.046725 ┆ -0.004171 ┆ … ┆ -0.024221 ┆ -0.104383 ┆ -0.0238   ┆ -0.026284 │
│ 4514 ┆ 0.051231  ┆ -0.0521   ┆ -0.018611 ┆ … ┆ -0.02048  ┆ -0.05934  ┆ -0.061295 ┆ -0.014093 │
│ 4514 ┆ 0.010886  ┆ -0.042959 ┆ 0.006008  ┆ … ┆ -0.037186 ┆ -0.029168 ┆ -0.086234 ┆ -0.078643 │
│ 4514 ┆ -0.033878 ┆ -0.005572 ┆ -0.003952 ┆ … ┆ -0.024736 ┆ -0.073763 ┆ -0.004471 ┆ -0.018087 │
└──────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
key_counts = df['KEY'].value_counts()
key_counts['count'].describe()

shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ value     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 10177.0   │
│ null_count ┆ 0.0       │
│ mean       ┆ 19.876486 │
│ std        ┆ 8.919119  │
│ min        ┆ 1.0       │
│ 25%        ┆ 13.0      │
│ 50%        ┆ 21.0      │
│ 75%        ┆ 29.0      │
│ max        ┆ 35.0      │
└────────────┴───────────┘

In [30]:
user_1 = df.filter(pl.col("KEY") == "4514")
user_1.shape

(30, 513)

In [32]:
dim_0 = user_1['dim_0'].to_numpy()

In [35]:
stat, p = shapiro(dim_0)
print(f"Shapiro-Wilk p-value: {p}")
if p > 0.05: print("Probably Gaussian")
else: print("Probably NOT Gaussian")

Shapiro-Wilk p-value: 0.5840537558805474
Probably Gaussian

In [39]:
def count_gaussian_dims(df: pl.DataFrame, threshold: int = 20, max_dims: int = 25):
    keys = df["KEY"].unique().to_list()
    results = []
    dim_cols = [f"dim_{i}" for i in range(min(max_dims, len(df.columns) - 1))]
    
    for key in tqdm(keys):
        sub_df = df.filter(pl.col("KEY") == key)
        
        if sub_df.height < threshold: continue

        count = 0
        for col in dim_cols:
            data = sub_df[col].to_numpy()

            if len(data) >= 3:
                try:
                    _, p = shapiro(data)
                    if p > 0.05: count += 1
                except Exception: pass  
        results.append((key, count))
    return pl.DataFrame(results, schema=["KEY", "VALID"])

In [40]:
gauss_check_df = count_gaussian_dims(df)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10177/10177 [00:24<00:00, 419.34it/s]
/var/folders/ty/p0wzwqf91jj_q1688wkh7cs80000gn/T/ipykernel_17261/10671821.py:21: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  return pl.DataFrame(results, schema=["KEY", "VALID"])

In [44]:
print(gauss_check_df['VALID'].describe())

shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ value     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 6322.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 44.650111 │
│ std        ┆ 3.34959   │
│ min        ┆ 19.0      │
│ 25%        ┆ 43.0      │
│ 50%        ┆ 45.0      │
│ 75%        ┆ 47.0      │
│ max        ┆ 50.0      │
└────────────┴───────────┘

In [46]:
gauss_check_df_25 = count_gaussian_dims(df, max_dims = 75)
print(gauss_check_df_25['VALID'].describe())

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10177/10177 [00:29<00:00, 342.71it/s]

shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ value     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 6322.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 67.029737 │
│ std        ┆ 4.618604  │
│ min        ┆ 31.0      │
│ 25%        ┆ 65.0      │
│ 50%        ┆ 68.0      │
│ 75%        ┆ 70.0      │
│ max        ┆ 75.0      │
└────────────┴───────────┘

/var/folders/ty/p0wzwqf91jj_q1688wkh7cs80000gn/T/ipykernel_17261/10671821.py:21: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  return pl.DataFrame(results, schema=["KEY", "VALID"])